# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Work Ethic
tagline:          'A Place for Social Innovation'
description:      'Highlighting the beauty and best practice in social innovation'
url:              http://jonathanhung.github.io/workethic/
baseurl:          /workethic
imgurl:          /workethic/assets/images

author:
  name:           'Jonathan Hung'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/jonathanhung/workethic
